
services:

  nginx:
    build:
      dockerfile: /nginx/Dockerfile.dev
      context: ./apps/website
    ports:
      - "3001:80"
    volumes:
      - ./apps/website/frontend/src:/usr/share/nginx/html
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_API_BACKEND_IP  
      - VLING_BACKEND_SERVICE_NAME=backend
      - VLING_FRONTEND_SERVICE_NAME=frontend

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/website/backend
    ports:
      - "47900:47900"
      - "47901:47901"
    volumes:
      - ./apps/website/backend:/catagent/apps/website/backend
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_API_BACKEND_IP
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - DEXTOOLS_API_KEY

  trader:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/trader
    volumes:
      - ./apps/trader/src:/apps/trader/src
    environment:
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - VLING_HELIUS_API_KEY
      - VLING_WALLET_PRIVATE_KEY
    depends_on:
      - postgres
      - redis

  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      - POSTGRES_PASSWORD=${VLING_ADMIN_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
     - vling-postgres-data:/home/postgres/pgdata/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    build:
      context: ./db/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - voidling-redis-data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  vling-postgres-data:
  vling-redis-data: