
services:

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./apps/website/frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_BACKEND_SERVICE_NAME=backend
      - VLING_FRONTEND_SERVICE_NAME=frontend
      - VLING_FRONTEND_SERVICE_NAME_UAT=frontend-uat
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/apache2:/etc/apache2:ro
    depends_on:
      - backend
    networks:
      - vling-network
      - vling-network-uat

  backend:
    build:
      dockerfile: Dockerfile
      context: ./apps/website/backend
    ports:
      - "47900:47900"
      - "47901:47901"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - DEXTOOLS_API_KEY
      - VLING_HELIUS_API_KEY
      - VLING_HYPERBOLIC_API_KEY
    depends_on:
      - redis
      - postgres
    networks:
      - vling-network

  trader:
    build:
      dockerfile: Dockerfile
      context: ./apps/trader
    volumes:
      - ./apps/trader/src:/apps/trader/src
    environment:
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - VLING_HELIUS_API_KEY
      - VLING_WALLET_PRIVATE_KEY
      - DEXTOOLS_API_KEY
    depends_on:
      - postgres
      - redis
    networks:
      - vling-network

  telegrambot:
    build:
      dockerfile: Dockerfile
      context: ./apps/telegrambot
    volumes:
      - ./apps/telegrambot/src:/apps/telegrambot/src
    environment:
      - VLING_TG_BOT_KEY
      - VLING_TG_BOT_KEY_TEST
      - VLING_TG_CHANNEL_ID
      - VLING_TG_CHANNEL_ID_TEST
      - GOD_TG_ACCOUNT
      - FIGURE_TG_ACCOUNT
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
    networks:
      - vling-network

  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      - POSTGRES_PASSWORD=${VLING_ADMIN_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
     - vling-postgres-data:/home/postgres/pgdata/data
    networks:
      - vling-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vling-network

  redis:
    build:
      context: ./db/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6380:6379"
      - "8001:8001"
    volumes:
      - vling-redis-data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - vling-network

volumes:
  vling-postgres-data:
  vling-redis-data:

networks:
  vling-network:
  vling-network-uat:
    name: vling-uat-network
    external: true