
services:

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/website/frontend
    ports:
      - "3001:80"
    volumes:
      - ./apps/website/frontend/src:/usr/share/nginx/html
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_BACKEND_SERVICE_NAME=backend
      - VLING_FRONTEND_SERVICE_NAME=frontend
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/website/backend
    ports:
      - "47900:47900"
      - "47901:47901"
    volumes:
      - ./apps/website/backend:/voidling/apps/website/backend
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - DEXTOOLS_API_KEY
      - VLING_HELIUS_API_KEY
      - VLING_HYPERBOLIC_API_KEY
    depends_on:
      - redis
      - postgres

  trader:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/trader
    volumes:
      - ./apps/trader/src:/apps/trader/src
    environment:
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - VLING_HELIUS_API_KEY
      - VLING_WALLET_PRIVATE_KEY
      - DEXTOOLS_API_KEY
    depends_on:
      - postgres
      - redis

  telegrambot:
    build:
      dockerfile: Dockerfile.dev
      context: ./apps/telegrambot
    volumes:
      - ./apps/telegrambot/src:/apps/telegrambot/src
    environment:
      - VLING_TG_BOT_KEY
      - VLING_TG_BOT_KEY_TEST
      - VLING_TG_CHANNEL_ID
      - VLING_TG_CHANNEL_ID_TEST
      - GOD_TG_ACCOUNT
      - FIGURE_TG_ACCOUNT
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis

  postgres:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      - POSTGRES_PASSWORD=${VLING_ADMIN_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
     - vling-postgres-data:/home/postgres/pgdata/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    build:
      context: ./db/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - vling-redis-data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  vling-postgres-data:
  vling-redis-data: