
services:

  frontend-uat:
    build:
      dockerfile: Dockerfile.uat
      context: ./apps/website/frontend
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_BACKEND_SERVICE_NAME=backend
      - VLING_FRONTEND_SERVICE_NAME=frontend
    depends_on:
      - backend-uat
    networks:
      - vling-network

  backend-uat:
    build:
      dockerfile: Dockerfile
      context: ./apps/website/backend
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - DEXTOOLS_API_KEY
      - VLING_HELIUS_API_KEY
      - VLING_HYPERBOLIC_API_KEY
    depends_on:
      - redis-uat
      - postgres-uat
    networks:
      - vling-network

  trader-uat:
    build:
      dockerfile: Dockerfile
      context: ./apps/trader
    volumes:
      - ./apps/trader/src:/apps/trader/src
    environment:
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
      - VLING_HELIUS_API_KEY
      - VLING_WALLET_PRIVATE_KEY
      - DEXTOOLS_API_KEY
    depends_on:
      - postgres-uat
      - redis-uat
    networks:
      - vling-network

  telegrambot-uat:
    build:
      dockerfile: Dockerfile
      context: ./apps/telegrambot
    volumes:
      - ./apps/telegrambot/src:/apps/telegrambot/src
    environment:
      - VLING_TG_BOT_KEY
      - VLING_TG_BOT_KEY_TEST
      - VLING_TG_CHANNEL_ID
      - VLING_TG_CHANNEL_ID_TEST
      - GOD_TG_ACCOUNT
      - FIGURE_TG_ACCOUNT
      - VLING_POSTGRES_URL=postgres
      - VLING_POSTGRES_CREDENTIALS
      - VLING_REDIS_URL=redis
    networks:
      - vling-network

  postgres-uat:
    image: timescale/timescaledb-ha:pg16
    restart: always
    environment:
      - POSTGRES_PASSWORD=${VLING_ADMIN_POSTGRES_PASSWORD}
    volumes:
     - vling-postgres-data:/home/postgres/pgdata/data
    networks:
      - vling-network

  adminer-uat:
    image: adminer
    restart: always
    ports:
      - "8084:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vling-network

  redis-uat:
    build:
      context: ./db/redis
      dockerfile: Dockerfile
    restart: always
    volumes:
      - vling-redis-data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - vling-network

volumes:
  vling-postgres-data:
  vling-redis-data:

networks:
  vling-network: