FROM node:18.13.0-bullseye-slim

#Working Dir
WORKDIR /frontend

COPY package*.json ./

RUN npm install

# Copy Source Files
COPY . .

#Expose the API port
EXPOSE 3000

FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf
COPY ./template/nginx.conf.template.dev /etc/nginx/templates/nginx.conf.template
COPY ./src /usr/share/nginx/html
EXPOSE 80



