FROM node:18.13.0-bullseye-slim

#Working Dir
WORKDIR /frontend

COPY package*.json ./

RUN npm install

# Copy Source Files
COPY . .

#Expose the API port
EXPOSE 3000

CMD [ "npm", "run", "startdev"]



